obj-${CONFIG_MYDRIVER_SUBSYS_DEMO} += demo_core.o
obj-${CONFIG_MYDRIVER_SUBSYS_DEMO} += demo_dev.o
obj-${CONFIG_MYDRIVER_SUBSYS_DEMO} += demo_interface.o
obj-${CONFIG_MYDRIVER_SUBSYS_DEMO} += demo_proc.o
obj-${CONFIG_MYDRIVER_SUBSYS_DEMO} += demo_sysfs.o

#demo-objs := demo_core.o demo_dev.o demo_interface.o demo_proc.o demo_sysfs.o

#demo-objs = demo_core.o
#demo-objs += demo_dev.o
#demo-objs += demo_interface.o
#demo-objs += demo_proc.o
#demo-objs += demo_sysfs.o

$(warning $(demo-objs))
obj-${CONFIG_MYDRIVER_SUBSYS_DEMO} += xxx_demo_device.o
obj-${CONFIG_MYDRIVER_SUBSYS_DEMO} += xxx_demo_driver.o
